name: alda_walker_walk
trainer:
  class: ALDA
  module: trainers.alda_trainer
  config:
    seed: 0
    use_depth: false
    use_data_aug: false
    batch_size: 128
    num_latents: 12
    values_per_latent: 12
    beta: 100
    n_train_steps: 500_000
    env:
      domain_name: walker
      task_name: walk
      frame_stack: 3
      action_repeat: 4
      episode_length: 1000
