name: alda_ball_in_cup_catch
trainer:
  class: ALDA
  module: trainers.alda_trainer
  config:
    seed: 0
    batch_size: 128
    num_latents: 12
    values_per_latent: 12
    beta: 100
    n_train_steps: 500_000
    env:
      domain_name: ball_in_cup
      task_name: catch
      frame_stack: 3
      action_repeat: 4
      episode_length: 1000
