name: sac_ae_walker_walk_randoverlay
trainer:
  class: SAC_AE
  module: trainers.sac_ae_trainer
  config:
    seed: 0
    n_train_steps: 1_000_000
    use_data_aug: false
    env:
      domain_name: walker
      task_name: walk
      frame_stack: 3
      action_repeat: 4
      episode_length: 1000
